### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by lucav90** [bitbull-team/magento2-module-instagramwidget#1]
Hi,

i have installed your module for Instagram photos but i don't view it in magento admin. Your module is a widget but i don't view it in the widget lists.
How can i resolve?

Another question: i have integrated your code manually in my magento source code and works but how can hide Instagram private data (userid,token)?
With your module, theese data are hidden to users?

Regards,

**Comment by nuovecode** [comment]
Hi @lucav90 ,

Thanks for the feedback. This module is called _widget_ because it is a _jQueryUI widget_ but has'nt the backend configuration. 
To use it you have to override view/frontend/templates/instagram-widget.phtml in your theme and replace the data with those of your instagram account. I wrote a post ( but it's in Italian :( https://www.bitbull.it/blog/sviluppare-un-widget-con-magento2-e-requirejs/)

We'll add soon the option to configure your instagram account from Magento2 backend.

**Comment by lucav90** [comment]
Hi @nuovecode,

yes ok. I have configurated the module by source code but i have a question.
Users read in source code of my website the token and userid of my Instagram account. 
How can i hide these data?

**Comment by nuovecode** [comment]
You're right. We have to.

**Comment by rodde177** [comment]
Hi, I added configuration for admin section and made pull request if you are interested in adding this functionality to your module :)

**Comment by nuovecode** [comment]
Great @rodde177 tnx! I'm watching your changes

**Comment by nuovecode** [comment]
Hi, I merged pull request of @rodde177. Thanks so much :) 
@lucav90 if you upgrade to 2.0.0 you can see the admin configurations

**Comment by nuovecode** [comment]
Hi @lucav90, I just checked the doc. Instagram doesn't have a public API for posting, it lets you get their data but not write your own. So  for the moment I decided to keep the call client side.

**Comment by lorenaramonda** [comment]
I set this as closed due to inactivity.
