### ISSUE TITLE
Square images

### ISSUE THREAD

**Issue by gabrielecontitaguali** [bitbull-team/magento2-module-instagramwidget#6]
Dear,

I installed your module on [this 2.1.2](https://www.malianta.com) installation but when i select squared images no feed is showing.

I don't know if this is related to magento's version.

Hope the developer can help: :)

Thank you

**Comment by nuovecode** [comment]
Hi! Any error in console?

**Comment by lorenaramonda** [comment]
Hi @gabrielecontitaguali, when you say
> i select squared images
you mean that you unchecked "Non square media:" checkbox into the migrations tab under manage client section at https://www.instagram.com/developer/?

And then, are you still experiencing the error? because the link you provide seems to have instagram feed working right now.

Thank you for your feedback!

**Comment by gabrielecontitaguali** [comment]
Dear,

sorry for late reply.

It seems like the image link is wrong.
@lorenaramonda the Non square media is checked as the image below:
![1](https://user-images.githubusercontent.com/35656405/36548246-0cda5446-17f0-11e8-83ec-e783471e26d8.jpg)

These are my settings on website backend:

![screenshot 2018-02-22 16 40 22](https://user-images.githubusercontent.com/35656405/36548308-3d90a7f2-17f0-11e8-93b0-c7c5e8fa81e5.png)


This is the error in console:
![screenshot 2018-02-22 16 43 14](https://user-images.githubusercontent.com/35656405/36548331-505533f8-17f0-11e8-947c-63b672081d88.png)


What I noticed is that if in the link we change the s320x320 with s150x150 then image appears:

![screenshot 2018-02-22 16 43 54](https://user-images.githubusercontent.com/35656405/36548371-6d6c3766-17f0-11e8-8fac-b61fdfd860a9.png)

![screenshot 2018-02-22 16 44 23](https://user-images.githubusercontent.com/35656405/36548382-73238042-17f0-11e8-9a3e-7b0c1411cbee.png)



Right now the issue is live on the website.

**Comment by lorenaramonda** [comment]
Ok, yes.
This happens since a couple of months when Instagram changed its URLs references. We used a trick to have squared picture at a higher resolution (320x320px), we get that by replacing 150 with 320 (https://github.com/bitbull-team/magento2-module-instagramwidget/blob/master/view/frontend/web/js/InstagramWidget.js#L73), but now this is not possible anymore because image URL throws a 403 error.

So I think we might switch again to the previous code, where that replacement was not done but squared images were just 150x150px, or we may considering a solution like this: https://humaan.com/blog/bigger-square-thumbnails-from-the-instagram-api/

Me and @nuovecode will get back soon with updates ;)

**Comment by lorenaramonda** [comment]
Hi @gabrielecontitaguali it should be fixed now, please check 4.3.0 version :)

**Comment by lorenaramonda** [comment]
I set this as closed due to inactivity. The new version has been test and solve this problem.
In case open another issue 🙂
